# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fishcurrent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentfish', models.IntegerField()),
                ('currentrate', models.IntegerField()),
                ('wrate', models.IntegerField(default='0')),
                ('clrate', models.IntegerField(default='0')),
                ('ccrate', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='fishmain',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fishname', models.CharField(max_length=100, unique=True)),
                ('fishdesc', models.CharField(max_length=5000)),
                ('fishurl', models.URLField()),
                ('fishtype', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='fishorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.fishmain')),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userissue', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mobileno', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=1000)),
                ('address2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.registration'),
        ),
        migrations.AddField(
            model_name='issue',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.registration'),
        ),
        migrations.AddField(
            model_name='fishorder',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.registration'),
        ),
        migrations.AddField(
            model_name='fishcurrent',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.fishmain'),
        ),
    ]
