# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0002_auto_20160316_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishcurrent',
            name='currentrate',
        ),
        migrations.AddField(
            model_name='fishmain',
            name='currentrate',
            field=models.IntegerField(default='0'),
        ),
    ]
