# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0006_auto_20160408_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishcurrent',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.fishcurrent'),
        ),
        migrations.AlterField(
            model_name='fishcurrent',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fish_market.fishmain'),
        ),
    ]
