# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0006_auto_20160408_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishcurrent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
