# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0007_auto_20160408_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='fishtype',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='fishcurrent',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.fishmain'),
        ),
        migrations.AlterField(
            model_name='fishcurrent',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.fishmain'),
        ),
    ]
