# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0008_auto_20160408_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='fishtype',
        ),
    ]
