# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0009_remove_cartitem_fishtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ftype',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
