# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0011_auto_20160408_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ftype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ftype',
        ),
        migrations.AlterField(
            model_name='fishcurrent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ftype',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.CartItem'),
        ),
    ]
