# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0013_auto_20160408_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ft',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
