# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0014_cartitem_ft'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('landmark', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=50)),
                ('cart_id', models.CharField(max_length=50)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_market.registration')),
            ],
        ),
    ]
