# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_market', '0015_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
